import { Share, Platform } from 'react-native';
import type { WeightEntry } from '@/utils/types';
import { formatDate, formatWeight } from '@/utils/formatters';

export async function exportWeightSummary(
  petName: string,
  entries: WeightEntry[],
): Promise<void> {
  if (entries.length === 0) {
    await Share.share({
      message: `${petName} - Weight History\n\nNo weight entries recorded yet.`,
    });
    return;
  }

  const sorted = [...entries].sort(
    (a, b) => new Date(a.measuredAt).getTime() - new Date(b.measuredAt).getTime(),
  );

  const latest = sorted[sorted.length - 1];
  const earliest = sorted[0];

  let summary = `${petName} - Weight History\n`;
  summary += `${'='.repeat(30)}\n\n`;
  summary += `Current: ${formatWeight(latest.weight, latest.unit)} (${formatDate(latest.measuredAt)})\n`;

  if (sorted.length >= 2) {
    const delta = latest.weight - earliest.weight;
    const sign = delta >= 0 ? '+' : '';
    summary += `Change: ${sign}${delta.toFixed(1)} ${latest.unit} since ${formatDate(earliest.measuredAt)}\n`;
  }

  summary += `\nAll Entries:\n`;
  summary += `${'-'.repeat(30)}\n`;

  sorted.forEach((entry, index) => {
    const prev = index > 0 ? sorted[index - 1] : null;
    let deltaText = '';
    if (prev) {
      const d = entry.weight - prev.weight;
      deltaText = ` (${d >= 0 ? '+' : ''}${d.toFixed(1)})`;
    }
    summary += `${formatDate(entry.measuredAt)}: ${formatWeight(entry.weight, entry.unit)}${deltaText}\n`;
  });

  summary += `\nTotal entries: ${entries.length}`;
  summary += `\nGenerated by Petto`;

  await Share.share(
    Platform.OS === 'ios'
      ? { message: summary }
      : { message: summary, title: `${petName} Weight History` },
  );
}

export async function shareText(title: string, message: string): Promise<void> {
  await Share.share(
    Platform.OS === 'ios'
      ? { message }
      : { message, title },
  );
}
