import React, { useCallback, useMemo, useRef, useState } from 'react';
import { View, Text, ScrollView, Share, Alert, Pressable } from 'react-native';
import { useNavigation, useRoute } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import type { RouteProp } from '@react-navigation/native';
import { captureRef } from 'react-native-view-shot';
import { ArrowLeft, Download, Share2 } from 'lucide-react-native';

import { usePets } from '@/hooks/usePets';
import { useAppStore } from '@/store/useAppStore';
import { Button, IconButton } from '@/components/ui';
import IDCardTemplate from '@/features/pet-id/components/IDCardTemplate';
import IDCardLight from '@/features/pet-id/components/IDCardLight';
import { colors } from '@/utils/colors';
import type { RootStackParamList } from '@/app/navigation/types';

type NavigationProp = NativeStackNavigationProp<RootStackParamList, 'PetIDCard'>;
type IDCardRouteProp = RouteProp<RootStackParamList, 'PetIDCard'>;

type CardTemplate = 'classic' | 'modern';

export default function PetIDCardScreen() {
  const navigation = useNavigation<NavigationProp>();
  const route = useRoute<IDCardRouteProp>();
  const { pets } = usePets();
  const ownerName = useAppStore((state) => state.ownerName);
  const ownerContact = useAppStore((state) => state.ownerContact);

  const [selectedPetId, setSelectedPetId] = useState<string>(route.params.petId);
  const [template, setTemplate] = useState<CardTemplate>('classic');
  const [isCapturing, setIsCapturing] = useState(false);
  const cardRef = useRef<View>(null);

  const pet = useMemo(() => {
    const found = pets.find((p) => p.id === selectedPetId);
    if (!found) return null;
    // Merge owner info from settings if not on the pet itself
    return {
      ...found,
      ownerName: found.ownerName ?? (ownerName || null),
      ownerContact: found.ownerContact ?? (ownerContact || null),
    };
  }, [pets, selectedPetId, ownerName, ownerContact]);

  const handleGoBack = useCallback(() => {
    navigation.goBack();
  }, [navigation]);

  const handleSelectPet = useCallback((id: string) => {
    setSelectedPetId(id);
  }, []);

  const handleSelectTemplate = useCallback((t: CardTemplate) => {
    setTemplate(t);
  }, []);

  const handleGeneratePNG = useCallback(async () => {
    if (!cardRef.current) return;

    setIsCapturing(true);
    try {
      const uri = await captureRef(cardRef, {
        format: 'png',
        quality: 1,
        result: 'tmpfile',
      });
      Alert.alert('Success', `ID card saved to: ${uri}`);
    } catch {
      Alert.alert('Error', 'Failed to generate ID card image.');
    } finally {
      setIsCapturing(false);
    }
  }, []);

  const handleShare = useCallback(async () => {
    if (!cardRef.current) return;

    setIsCapturing(true);
    try {
      const uri = await captureRef(cardRef, {
        format: 'png',
        quality: 1,
        result: 'tmpfile',
      });
      await Share.share({
        url: uri,
        message: `${pet?.name ?? 'Pet'} ID Card - Generated by Petto`,
      });
    } catch {
      Alert.alert('Error', 'Failed to share ID card.');
    } finally {
      setIsCapturing(false);
    }
  }, [pet]);

  if (!pet) {
    return (
      <View className="flex-1 bg-cream dark:bg-dark-bg items-center justify-center">
        <Text className="text-base text-muted dark:text-muted-dark">Pet not found</Text>
      </View>
    );
  }

  return (
    <View className="flex-1 bg-cream dark:bg-dark-bg">
      {/* Header */}
      <View className="flex-row items-center px-4 pt-14 pb-3 bg-white dark:bg-dark-card">
        <IconButton
          icon={<ArrowLeft size={22} color={colors.text} />}
          onPress={handleGoBack}
          accessibilityLabel="Go back"
          className="mr-3"
        />
        <Text className="text-xl font-bold text-text-primary dark:text-text-dark">
          Pet ID Card
        </Text>
      </View>

      <ScrollView
        className="flex-1"
        contentContainerStyle={{ padding: 16, paddingBottom: 40, alignItems: 'center' }}
        showsVerticalScrollIndicator={false}
      >
        {/* Pet Selector */}
        {pets.length > 1 && (
          <ScrollView
            horizontal
            showsHorizontalScrollIndicator={false}
            className="mb-5 self-start"
          >
            {pets.map((p) => {
              const isSelected = p.id === selectedPetId;
              return (
                <Pressable
                  key={p.id}
                  onPress={() => handleSelectPet(p.id)}
                  accessibilityLabel={`Select ${p.name}`}
                  accessibilityRole="button"
                  accessibilityState={{ selected: isSelected }}
                  className={`px-4 py-2 mr-2 rounded-xl ${
                    isSelected
                      ? 'bg-primary-500 dark:bg-primary-400'
                      : 'bg-white dark:bg-dark-card border border-gray-200 dark:border-gray-700'
                  }`}
                >
                  <Text
                    className={`text-sm font-medium ${
                      isSelected
                        ? 'text-white'
                        : 'text-text-primary dark:text-text-dark'
                    }`}
                  >
                    {p.name}
                  </Text>
                </Pressable>
              );
            })}
          </ScrollView>
        )}

        {/* Template Selector */}
        <View className="flex-row mb-6 self-center">
          <Pressable
            onPress={() => handleSelectTemplate('classic')}
            accessibilityLabel="Classic template"
            accessibilityRole="button"
            accessibilityState={{ selected: template === 'classic' }}
            className={`px-5 py-2.5 rounded-l-xl border ${
              template === 'classic'
                ? 'bg-primary-500 dark:bg-primary-400 border-primary-500'
                : 'bg-white dark:bg-dark-card border-gray-200 dark:border-gray-700'
            }`}
          >
            <Text
              className={`text-sm font-semibold ${
                template === 'classic' ? 'text-white' : 'text-text-primary dark:text-text-dark'
              }`}
            >
              Classic
            </Text>
          </Pressable>
          <Pressable
            onPress={() => handleSelectTemplate('modern')}
            accessibilityLabel="Modern template"
            accessibilityRole="button"
            accessibilityState={{ selected: template === 'modern' }}
            className={`px-5 py-2.5 rounded-r-xl border ${
              template === 'modern'
                ? 'bg-primary-500 dark:bg-primary-400 border-primary-500'
                : 'bg-white dark:bg-dark-card border-gray-200 dark:border-gray-700'
            }`}
          >
            <Text
              className={`text-sm font-semibold ${
                template === 'modern' ? 'text-white' : 'text-text-primary dark:text-text-dark'
              }`}
            >
              Modern
            </Text>
          </Pressable>
        </View>

        {/* Card Preview */}
        <View ref={cardRef} collapsable={false}>
          {template === 'classic' ? (
            <IDCardTemplate pet={pet} />
          ) : (
            <IDCardLight pet={pet} />
          )}
        </View>

        {/* Action Buttons */}
        <View className="flex-row gap-3 mt-8 w-full max-w-[340px]">
          <View className="flex-1">
            <Button
              variant="primary"
              size="lg"
              onPress={handleGeneratePNG}
              loading={isCapturing}
              leftIcon={<Download size={18} color="#FFFFFF" />}
              accessibilityLabel="Generate PNG"
              className="w-full"
            >
              Generate PNG
            </Button>
          </View>
          <View className="flex-1">
            <Button
              variant="outline"
              size="lg"
              onPress={handleShare}
              loading={isCapturing}
              leftIcon={<Share2 size={18} color={colors.primary[500]} />}
              accessibilityLabel="Share ID card"
              className="w-full"
            >
              Share
            </Button>
          </View>
        </View>
      </ScrollView>
    </View>
  );
}
